<script>
  import LoadingTask from './LoadingTask.svelte';
  import LoadingSearch from './LoadingSearch.svelte';
  const feedbackText = { running: 'Sample operation in progress…', complete: 'Sample operation complete.', canceled: 'Sample operation canceled. Try again.' };
</script>
{#snippet feedback(state)}<p class="loading-feedback" role="status" aria-atomic="true">{feedbackText[state] ?? 'Sample operation · ready'}</p>{/snippet}
{#snippet skeleton()}<div class="loading-skeleton" aria-hidden="true"><span></span><span></span><span></span></div>{/snippet}
{#snippet taskButton(idle, working, variant = '')}<LoadingTask>{#snippet children({ busy, state, start })}<div class="od-stack loading-button-stack loading-demo"><button class={['btn', variant]} type="button" aria-label={busy ? working : idle} onclick={start} disabled={busy} aria-busy={busy}><span class="spinner" aria-hidden="true" class:is-on={busy}></span><span class="btn-label" class:is-hidden={busy}>{idle}</span></button>{@render feedback(state)}</div>{/snippet}</LoadingTask>{/snippet}
{#snippet overlayExample({ example, heading, content, overlay, action, empty = false })}<LoadingTask>{#snippet children({ busy, state, start, cancel })}<article class="loading-example od-stack loading-demo" data-example={example}><h3>{heading}</h3><div class={['loading-stage', empty && 'loading-empty']} aria-busy={busy} data-state={state}>
      <div class="loading-content od-stack" inert={busy} aria-hidden={busy}><strong>{content}</strong><p class="loading-hint">Local sample content; no service connection.</p>{@render skeleton()}</div>
      <div class="loading-overlay" hidden={!busy}><span class="spinner" aria-hidden="true" data-size="lg"></span><strong>{overlay}</strong><p class="loading-hint">Sample operation in progress</p>{@render skeleton()}</div>
    </div><div class="od-cluster"><button class="btn" type="button" aria-label={busy ? 'Loading…' : action} onclick={start} disabled={busy} aria-busy={busy}><span class="spinner" aria-hidden="true" class:is-on={busy}></span><span class="btn-label" class:is-hidden={busy}>{action}</span></button><button class="btn" type="button" onclick={cancel} hidden={!busy}>Cancel</button></div>{@render feedback(state)}</article>{/snippet}</LoadingTask>{/snippet}
<section class="section" data-od-id="spinners" id="spinners"><div class="section-head"><h2 class="section-title">Spinners</h2><span class="section-id">.spinner · .loading-dots · aria-busy</span></div><p class="field-legend">Sample loading patterns · controls complete locally and can be repeated</p><div class="od-grid loading-gallery">
  <article class="loading-example od-stack" data-example="basic"><h3>Basic spinner</h3><div class="loading-center" role="status"><div class="od-cluster"><span class="spinner" aria-hidden="true" data-size="sm"></span><span class="spinner" aria-hidden="true"></span><span class="spinner" aria-hidden="true" data-size="lg"></span><span class="spinner" aria-hidden="true" data-size="xl"></span></div><span class="loading-hint">Loading · 12 / 16 / 24 / 32px</span></div></article>
  <article class="loading-example od-stack" data-example="buttons"><h3>Spinners in buttons</h3><div class="od-cluster">{@render taskButton('Process sample', 'Processing…', 'primary')}{@render taskButton('Load sample', 'Processing…')}<LoadingTask>{#snippet children({ busy, state, start })}<div class="od-stack loading-demo"><button class="btn icon" type="button" aria-label="Refresh sample" onclick={start} disabled={busy} aria-busy={busy}><span class="spinner" aria-hidden="true" class:is-on={busy}></span><span class="btn-label" class:is-hidden={busy}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20 7v5h-5M4 17v-5h5M6 6a8 8 0 0 1 13 2M18 18a8 8 0 0 1-13-2"></path></svg></span></button>{@render feedback(state)}</div>{/snippet}</LoadingTask></div></article>
  <article class="loading-example od-stack" data-example="badges"><h3>Spinners in badges</h3><div class="od-cluster"><span class="pill loading-badge inverted"><span class="spinner" aria-hidden="true" data-size="sm"></span>Updating</span><span class="pill loading-badge"><span class="spinner" aria-hidden="true" data-size="sm"></span>Syncing</span><span class="pill loading-badge running-pill"><span class="spinner" aria-hidden="true" data-size="sm"></span>Loading</span><span class="pill loading-badge missing"><span class="spinner" aria-hidden="true" data-size="sm"></span>Retrying</span><span class="pill loading-badge ok-pill"><span class="spinner" aria-hidden="true" data-size="sm"></span>Syncing</span></div><p class="loading-hint">Sample pending states</p></article>
  <LoadingSearch/>
  {@render overlayExample({ example: 'empty-state', heading: 'Loading empty state', content: 'No sample projects loaded', overlay: 'Loading projects…', action: 'Load sample projects', empty: true })}
  <article class="loading-example od-stack" data-example="button-states"><h3>Button loading states</h3><div class="od-cluster">{@render taskButton('Save sample', 'Saving…', 'primary')}{@render taskButton('Load sample', 'Loading…')}{@render taskButton('Process sample', 'Processing…', 'text')}</div></article>
  {@render overlayExample({ example: 'content-overlay', heading: 'Content loading overlay', content: 'Sample evaluation results', overlay: 'Refreshing data…', action: 'Refresh sample' })}
  {@render overlayExample({ example: 'full-surface', heading: 'Full-surface loading', content: 'Sample workspace', overlay: 'Setting up workspace…', action: 'Set up sample', empty: true })}
  <article class="loading-example od-stack" data-example="inline"><h3>Inline loading status</h3><div class="od-stack"><div class="od-row" role="status" data-loading-tone="key"><span class="spinner" aria-hidden="true" data-size="sm"></span><span>Checking availability…</span></div><div class="od-row" role="status" data-loading-tone="ok"><span class="spinner" aria-hidden="true" data-size="sm"></span><span>Connected · syncing sample data</span></div><div class="od-row" role="status" data-loading-tone="warn"><span class="spinner" aria-hidden="true" data-size="sm"></span><span>Reconnecting · sample attempt</span></div></div></article>
  <article class="loading-example od-stack" data-example="dots"><h3>Animated loading dots</h3><div class="loading-center" role="status"><span class="loading-dots" aria-hidden="true"><i></i><i></i><i></i></span><span class="loading-hint">Waiting for sample response…</span></div></article>
  {@render overlayExample({ example: 'card-overlay', heading: 'Card loading overlay', content: 'Sample suite summary', overlay: 'Refreshing card…', action: 'Refresh card' })}
  <article class="loading-example od-stack" data-example="colours"><h3>Semantic spinner colours</h3><div class="od-cluster"><span class="od-row" data-loading-tone="key"><span class="spinner" aria-hidden="true"></span><span>Working</span></span><span class="od-row" data-loading-tone="ok"><span class="spinner" aria-hidden="true"></span><span>Syncing</span></span><span class="od-row" data-loading-tone="bad"><span class="spinner" aria-hidden="true"></span><span>Retrying</span></span><span class="od-row" data-loading-tone="warn"><span class="spinner" aria-hidden="true"></span><span>Reconnecting</span></span></div><p class="loading-hint">State labels accompany colour.</p></article>
</div></section>
