export const PROMPT_SECTIONS = [
  {
    id: 'role',
    title: 'Role',
    text: 'Extract invoice data from raw text into the specified JSON schema.',
  },
  {
    id: 'output',
    title: 'Output Format',
    text: '- **Output valid raw JSON only. Follow exact schema.** No markdown blocks, no explanations outside the JSON.\n- Include a `__reasoning__` field as the first item containing the Reconciliation Summary defined below.',
  },
  {
    id: 'constraints',
    title: 'Constraints and Formatting',
    text: [
      '- **Input Structure:** Before extracting any field, reconstruct the source`s line structure by treating escaped line-break markers as actual boundaries.',
      '- **Missing Data:** Set missing strings/dates to JSON `null` values, not the string "null" and not empty strings. Set missing numeric amounts to `0.0`. Set missing arrays to `[]`. Do not invent data.',
      '- **Schema Type Markers:** Empty strings in the JSON schema below indicate string-typed fields.',
      '- **Dates:** ISO 8601 (`YYYY-MM-DD`).',
      '- **Numbers:** Float format (e.g., `1234.56`). Normalize `,` to `.`.',
      '- **Number Format:** Handle UK/European invoice number formats carefully:',
      '  - `3.245.76` means 3245.76 (dot = thousands separator)',
      '  - `2,224.56` means 2224.56 (comma = thousands separator)',
      '  - Always check the header totals to verify your number parsing is correct.',
      '- **Currency:** 3-letter ISO 4217. Infer from symbols/context.',
    ].join('\n'),
  },
  {
    id: 'recon',
    title: 'Reconciliation Summary',
    text: [
      'The `__reasoning__` field must contain ONLY this compact summary to condition calculations before emitting JSON:',
      '- `CURRENCY`: 3-letter ISO code inferred from symbols/context.',
      '- `BANK`: `IBAN=<val> SWIFT=<val> ACCOUNTS=<semicolon-separated vendor accounts>`',
      '- `RATES`: Map tax codes/rates from document summary table (e.g., `A=19% B=0% DEFAULT=19%`).',
      '- `LINES`: Compact line items `id|snippet|amount|rate_code`',
      '- `SUM`: Arithmetic line summation `val1 + val2 + ... = line_sum`.',
      '- `TOTALS`: `line_sum=<sum> subtotal=<header net> tax=<header tax> total=<header gross>`',
      '- `BASIS`: `NET_BASED` if `line_sum ~= subtotal`. `GROSS_BASED` if `line_sum ~= total`.',
      '- `RECON`: `subtotal + tax + rounding ~= total`',
    ].join('\n'),
  },
  {
    id: 'rules',
    title: 'Extraction Rules',
    text: [
      '1. Document Classification',
      '- Set `is_invoice` to `true` if the text contains any financial billing information (e.g., totals, taxes, line item prices) indicating a request for payment. Set to `false` for purely operational documents.',
      '- Set `is_credit_note` to `true` if the document title, heading, or reference lines identify it as a credit note, credit memo, or credit invoice (in any language).',
      '',
      '2. Purchase Order',
      'Actively search the entire document for buyer references (e.g., "Your Order", "PO No.", "Cust. Part").',
      '- **Header `po_reference`:** Extract and aggregate ALL unique PO numbers found anywhere in the document. Concatenate them using a semicolon with no spaces.',
      '',
      '3. Dates',
      '- `invoice_date`: Use date labeled `Invoice Date`, `Document Date`, or `Date`. If multiple, use nearest top.',
      '- `due_date`: Extract the explicit due date when present. Otherwise, derive it from the stated payment terms by calculating `invoice_date + N days`.',
      '',
      '4. Vendor',
      'Use "Bank Details", "Remit To", or "Pay To" entity. Exclude "Bill To" / "Ship To".',
      '- `vendor_tax_id`: Extract supplier VAT/tax registration number when available.',
      '',
      '5. Customer',
      '- `customer_tax_id`: Extract buyer/customer VAT/tax registration number when available.',
      '- `customer_address`: Extract buyer/customer address block that identifies the receiving company.',
      '',
      '6. Received Bank Accounts',
      'Extract vendor/remittance bank account numbers from payment sections such as "Bank Details", "Remit To", "Pay To", "IBAN", or "Account Number". Return them in `received_bank_accounts` as a semicolon-separated string in reading order.',
      '',
      '7. Invoice Recipient',
      'Extract only a natural person explicitly addressed on the customer/buyer side (e.g., "Attention", "Attn", "FAO", "z.Hd."). Return the complete name only.',
      '- Do not use `Our Reference` or supplier-side contacts. If no qualifying person exists, return `null`.',
      '',
      '8. Rounding Amount',
      'Extract any explicit invoice rounding adjustment at header level into `rounding_amount`.',
      '- Use signed value. Example: +0.02 for round-up, -0.02 for round-down.',
      '- If no explicit rounding row/field is present, return `0.0`.',
      '',
      '9. Line Items',
      '- `line_id`: Integer, 1-based.',
      '- `description`: Capture item or service text verbatim, including identifiers or discount text that are part of the line.',
      '- `quantity`, `unit_of_measure`, `unit_price`: Extract as found.',
      '- **Line-level `line_po_reference`:** Use an explicit same-line PO when present; otherwise use the nearest preceding block-level buyer PO in reconstructed reading order.',
      '- `line_part_no`: Extract the explicit item code, manufacturer part number, catalog number, or SKU identifier tied to the specific line item.',
      '- `tax_rate`: Line tax rate percentage (e.g., 20.0). Resolve from line marker via RATES or document tax summary; if missing, use DEFAULT.',
      '- `net_amount`, `tax_amount`, `gross_amount`: Compute strictly from the established BASIS and line tax rate.',
    ].join('\n'),
  },
  {
    id: 'schema',
    title: 'JSON Schema',
    text: [
      '{',
      '  "__reasoning__": "CURRENCY: EUR\\nBANK: IBAN=… SWIFT=…\\nRATES: A=19% B=0% DEFAULT=19%\\n…",',
      '  "main": [{',
      '    "is_invoice": true, "is_credit_note": false,',
      '    "invoice_id": "", "po_reference": "",',
      '    "invoice_date": "", "due_date": "",',
      '    "vendor_name": "", "vendor_tax_id": "",',
      '    "customer_name": "", "customer_tax_id": "", "customer_address": "",',
      '    "received_bank_accounts": "", "invoice_recipient": "",',
      '    "subtotal": 0.0, "tax": 0.0, "total": 0.0, "rounding_amount": 0.0,',
      '    "currency": "",',
      '    "payment_details": [{"iban": "", "swift": ""}]',
      '  }],',
      '  "line_items": [{',
      '    "line_id": 1, "description": "", "quantity": 0,',
      '    "line_part_no": "", "line_part_no_description": "", "line_po_reference": "",',
      '    "unit_of_measure": "", "unit_price": 0.0,',
      '    "gross_amount": 0.0, "net_amount": 0.0, "tax_amount": 0.0, "tax_rate": 0.0',
      '  }]',
      '}',
    ].join('\n'),
  },
];

export const SYSTEM_PROMPT = PROMPT_SECTIONS
  .map((section) => `### ${section.title}\n${section.text}`)
  .join('\n\n');

export const SAMPLE_RESULT = {
  __reasoning__: [
    'CURRENCY: USD',
    'BANK: IBAN=null SWIFT=null ACCOUNTS=',
    'RATES: DEFAULT=0%',
    'LINES: 1|Bearing assembly|6200.00|0 2|Hydraulic coupling|8632.75|0',
    'SUM: 6200.00 + 8632.75 = 14832.75',
    'TOTALS: line_sum=14832.75 subtotal=14832.75 tax=0.00 total=14832.75',
    'BASIS: NET_BASED',
    'RECON: 14832.75 + 0.00 + 0.00 = 14832.75',
  ].join('\n'),
  main: [
    {
      is_invoice: true,
      is_credit_note: false,
      invoice_id: 'INV-2024-0871',
      po_reference: null,
      invoice_date: '2024-11-03',
      due_date: '2024-12-03',
      vendor_name: 'Northwind Industrial',
      vendor_tax_id: 'SE556000000001',
      customer_name: 'Contoso Manufacturing AB',
      customer_tax_id: null,
      customer_address: 'Box 114, 431 22 Molndal, Sweden',
      received_bank_accounts: null,
      invoice_recipient: null,
      subtotal: 14832.75,
      tax: 0,
      total: 14832.75,
      rounding_amount: 0,
      currency: 'USD',
      payment_details: [],
    },
  ],
  line_items: [
    {
      line_id: 1,
      description: 'Bearing assembly',
      quantity: 2,
      line_part_no: 'AX-4400',
      line_po_reference: '',
      unit_of_measure: 'EA',
      unit_price: 3100,
      gross_amount: 6200,
      net_amount: 6200,
      tax_amount: 0,
      tax_rate: 0,
    },
    {
      line_id: 2,
      description: 'Hydraulic coupling',
      quantity: 4,
      line_part_no: 'BR-1120',
      line_po_reference: '',
      unit_of_measure: 'EA',
      unit_price: 2158.1875,
      gross_amount: 8632.75,
      net_amount: 8632.75,
      tax_amount: 0,
      tax_rate: 0,
    },
  ],
};

export const SAMPLE_OCR_TEXT = [
  'INVOICE',
  'Northwind Industrial',
  'VAT SE556000000001',
  'Invoice INV-2024-0871',
  'Issued 2024-11-03',
  'Due 2024-12-03',
  'NET 30 DAYS',
  '',
  'Bill to: Contoso Manufacturing AB',
  'Box 114, 431 22 Molndal, Sweden',
  '',
  'Line 1  AX-4400  qty 2   6200.00',
  'Line 2  BR-1120  qty 4   8632.75',
  '',
  'Subtotal 14832.75  VAT 0.00',
  'TOTAL DUE  14832.75 USD',
].join('\n');

export const SAMPLE_DOCUMENT = { name: 'northwind-0871.pdf', size: 212 * 1024 };

export const MODELS = {
  'gpt-5.1': { input: 1.25, output: 10, note: 'Default · recipe.json' },
  'gpt-5.2': { input: 1.75, output: 14, note: 'Previous flagship' },
  'gpt-5.6-luna': { input: 0.2, output: 1.2, note: 'Fast, low cost' },
};

export const DEFAULT_MODEL = 'gpt-5.1';
